version: "3.8"

services:
  # Auth service
  gleam_auth:
    build: .
    ports:
      - "8000:8000"
    environment:
      # will update later
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: auth_database
      SECRET_KEY: temp_secret
    depends_on:
      - postgres  # Ensure Postgres is started before Gleam

  # Postgres database
  postgres:
    image: postgres:latest
    ports:
    - "5433:5433"
    command: postgres -p 5433
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistant storage for Postgres data
networks:
  backend:
    external: true

volumes:
  # Persistent storage volume for Postgres data
  postgres_data: {}