name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push auth service
      - name: Build and push auth service
        uses: docker/build-push-action@v5
        with:
          context: ./authentication-service
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/authentication-service:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/authentication-service:latest
